name: adventofcode2020
description: Advent of Code 2020
version: 0.0.1
author: yudansha

environment:
    sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
    pedantic: ^1.10.0-nullsafety.2
    test: ^1.16.0-nullsafety.7
    mockito: ^4.1.3